# ->->->->-> Primary <-<-<-<-<-
arch: "resnet20s"
exp_name: "CIFAR10_resnet20s_Unstructured_BiP_K0.1"
result_dir: "./trained_models"
num_classes: 10
exp_mode: "finetune"
layer_type: "unstructured"
normalize: True

k: 0.1

# ->->->->-> Train <-<-<-<-<-
trainer: "base"
epochs: 100
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0005
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1

# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 128
test_batch_size: 128
data_dir: "./data"
data_fraction: 1.0


# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100