# ->->->->-> Primary <-<-<-<-<-
arch: "resnet20s"
exp_name: "CIFAR10_resnet20s_Pretrain"
result_dir: "./trained_models"
num_classes: 10
image_dim: 32
exp_mode: "pretrain"
layer_type: "dense"
normalize: True

# ->->->->-> Train <-<-<-<-<-
trainer: "base"
epochs: 200
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0005
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1

# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 128
test_batch_size: 128
data_dir: "./data"


# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100